/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExampleRouteImport } from './routes/example'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PeopleIndexRouteImport } from './routes/people/index'
import { Route as PeopleAddRouteImport } from './routes/people/add'
import { Route as PeoplePeopleIdRouteImport } from './routes/people/$peopleId'
import { Route as PeoplePeopleIdEditRouteImport } from './routes/people/$peopleId_.edit'

const ExampleRoute = ExampleRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleAddRoute = PeopleAddRouteImport.update({
  id: '/people/add',
  path: '/people/add',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplePeopleIdRoute = PeoplePeopleIdRouteImport.update({
  id: '/people/$peopleId',
  path: '/people/$peopleId',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplePeopleIdEditRoute = PeoplePeopleIdEditRouteImport.update({
  id: '/people/$peopleId_/edit',
  path: '/people/$peopleId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/example': typeof ExampleRoute
  '/people/$peopleId': typeof PeoplePeopleIdRoute
  '/people/add': typeof PeopleAddRoute
  '/people': typeof PeopleIndexRoute
  '/people/$peopleId/edit': typeof PeoplePeopleIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/example': typeof ExampleRoute
  '/people/$peopleId': typeof PeoplePeopleIdRoute
  '/people/add': typeof PeopleAddRoute
  '/people': typeof PeopleIndexRoute
  '/people/$peopleId/edit': typeof PeoplePeopleIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/example': typeof ExampleRoute
  '/people/$peopleId': typeof PeoplePeopleIdRoute
  '/people/add': typeof PeopleAddRoute
  '/people/': typeof PeopleIndexRoute
  '/people/$peopleId_/edit': typeof PeoplePeopleIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/example'
    | '/people/$peopleId'
    | '/people/add'
    | '/people'
    | '/people/$peopleId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/example'
    | '/people/$peopleId'
    | '/people/add'
    | '/people'
    | '/people/$peopleId/edit'
  id:
    | '__root__'
    | '/'
    | '/example'
    | '/people/$peopleId'
    | '/people/add'
    | '/people/'
    | '/people/$peopleId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExampleRoute: typeof ExampleRoute
  PeoplePeopleIdRoute: typeof PeoplePeopleIdRoute
  PeopleAddRoute: typeof PeopleAddRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  PeoplePeopleIdEditRoute: typeof PeoplePeopleIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/example': {
      id: '/example'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof ExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/add': {
      id: '/people/add'
      path: '/people/add'
      fullPath: '/people/add'
      preLoaderRoute: typeof PeopleAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$peopleId': {
      id: '/people/$peopleId'
      path: '/people/$peopleId'
      fullPath: '/people/$peopleId'
      preLoaderRoute: typeof PeoplePeopleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$peopleId_/edit': {
      id: '/people/$peopleId_/edit'
      path: '/people/$peopleId/edit'
      fullPath: '/people/$peopleId/edit'
      preLoaderRoute: typeof PeoplePeopleIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExampleRoute: ExampleRoute,
  PeoplePeopleIdRoute: PeoplePeopleIdRoute,
  PeopleAddRoute: PeopleAddRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  PeoplePeopleIdEditRoute: PeoplePeopleIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
